### PR TITLE
Added fixes to process metrics

### PR DESCRIPTION
**Pull request by adnanrahic**
@megastef I've added the `pidusage-tree` module to this PR and added tests to make sure it works. We have some strange behavior with not gathering `child_process` metrics for CPU, memory, and uptime.

TODO:
Figure out why gathering `child_process` metrics is failing.

### CODE REVIEW

**Comment by adnanrahic** [comment]
This should now be a stable version that will gather and ship metrics. What is yet to be done is to check out the rollup function in the chartbuilder and figure out how it works. There seems to be some strange behavior there.

**Comment by emir-arnautovic** [comment]
Rollup function can be set explicitly in chart definition or implicitly by setting metric type (gauge or counter) in metric meta info.

**Comment by adnanrahic** [comment]
Update: We have an issue with the `child_process` tags. For some reason, they are not sent. I'm debugging why.

**Comment by adnanrahic** [comment]
Update: Fixed by adding `process.name` tag to add a grouping method for child processes. This feature is ready.
Todo: Need to sync with team regarding which tag names to use. Halting progress on this PR until then.

**Comment by adnanrahic** [comment]
Adding a list of tag names and metric names for reference (this will be changed in the near future):

Tags:

- process.pid
- process.ppid
- nodejs.process.type
- nodejs.process.name

Metrics:

- nodejs.process.count
- nodejs.process.uptime
- nodejs.process.cpu.percent
- nodejs.process.memory

**Pull request merged**
