### PR TITLE
feat: domain handling

### PR DESCRIPTION
**Pull request by AVVS**
We’ve recently integrated spam-agent-node for our production nodejs app monitoring - its a restify 4.x based http webserver. After we’ve integrated monitoring we’ve noticed that our memory was leaking. Upon investigation of heap dumps we’ve discovered that all the requests and responses are retained in memory and our bound to it’s Domain handler, which in turn is retained by existing timer, which is bound to the domain during domain.add(req) call and is originally created when patching http(s)Server in the spa agent, this creates a circular reference and a memory leak and effectively makes usage of the product impossible as we now have to restart the servers every day in order for them to operate.

A few screenshots and investigation paths:

```
spm-agent-node (https://github.com/sematext/spm-agent-nodejs/blob/master/lib/httpServerAgent.js#L30)
                               ^ measure/Timer (https://github.com/felixge/node-measured/blob/master/lib/metrics/Timer.js#L10)
                               ^ measure/Meter (https://github.com/felixge/node-measured/blob/master/lib/metrics/Meter.js#L7)
```

screen shot 2017-03-07 at 10 00 39 am
screen shot 2017-03-07 at 10 00 07 am

This PR makes sure that we exit current domain. The whole thing is really buggy, but this gets the job done. I've been running the server for the past several hours and memory is not leaking anymore

### CODE REVIEW

**Comment by otisg** [comment]
Looks like this somehow broke the build, @AVVS. We'll need to have a look.

**Comment by AVVS** [comment]
@otisg noticed a problem with stats being overwritten. If it's not too much hassle - I can add standard eslint instead of jshint as more modern approach

**Comment by otisg** [comment]
> I can add standard eslint instead of jshint as more modern approach
What say you, @megastef ?

**Comment by AVVS** [comment]
Should all be good now, please review/comment/merge ;)

**Comment by AVVS** [comment]
actually that interval that wasnt working before helped fix the leak. this doesnt really solve the issue yet, will work on it a bit more

**Comment by AVVS** [comment]
seems like the `ctx.stats = Measured.createCollection()` is the root cause of this or smth

**Comment by megastef** [comment]
Thanks for the contribution! @AVVS as far I know domains are deprecated see https://github.com/nodejs/node/issues/66 and https://nodejs.org/api/domain.html, and this PR would add domain handling - I just wonder if we would create here a problem for future node versions.

**Comment by megastef** [comment]
Could we remove yarn.lock? https://github.com/AVVS/spm-agent-nodejs/blob/4faffe52d639ddfb1cd7692530c8bf7c44ff21ca/yarn.lock

**Comment by AVVS** [comment]
@megastef its up to you, for me it works much faster than general `npm i --production` and allows to pin all deps while making sure they wont update to something unexpected

**Comment by megastef** [comment]
Sure I see the value in it. We would need to maintain the yarn.lock file, I'm just afraid that we forget to update it - so we need a script to generate it before release.

**Comment by AVVS** [comment]
just use yarn for managing deps. They have just as good tooling - yarn will manage package.json for you

This is similar no `npm-check -u`

alias ycheck='yarn upgrade-interactive'

yarn add <pkg> to add to deps
yarn add <pkg> -D to add to dev

**Pull request merged**
