### PR TITLE
http.createServer and https.createServer accepts more than 1 parameter

### PR DESCRIPTION
**Pull request by ravenjohn**
This will fix the bug on https

### CODE REVIEW

**Comment by megastef** [comment]
Thanks for submitting this pull request! The actual error was on another place, and the pull request had an issue with regular http as far I have seen.  

Please check changes and comments in https://github.com/sematext/spm-agent-nodejs/commit/dc280432ad20398f5054430df60d6f95cd5812f1

If you like to test it install using "npm i sematext/spm-agent-nodejs"  - it's currently not published on npm.

**Comment by ravenjohn** [comment]
Hi @megastef that was actually my first pull request. https://github.com/sematext/spm-agent-nodejs/pull/1/files.

I thought everything is fixed after but it wasn't. I figured out it's also because it's not passing all arguments on `origHttpsCreateServer`.

**Comment by megastef** [comment]
Hi @ravenjohn is the new version working for you?

**Comment by ravenjohn** [comment]
Hi @megastef it's not. There's still a bug: https://github.com/sematext/spm-agent-nodejs/commit/dc280432ad20398f5054430df60d6f95cd5812f1

**Comment by megastef** [comment]
Sorry - I had it on disk but not commited here. Just published.

**Pull request closed without merging**
